from finance_tracker_project.controllers.banks_controller import BanksController
from finance_tracker_project.controllers.sessions_controller import SessionsController
from finance_tracker_project.controllers.transactions_controller import TransactionsController
from finance_tracker_project.repositories.banks_repository import BanksRepository
from finance_tracker_project.repositories.transactions_repository import TransactionsRepository
from finance_tracker_project.services.auths_service import AuthsService
from finance_tracker_project.services.banks_service import BankAccountsService
from finance_tracker_project.services.reports_service import ReportsService
from finance_tracker_project.repositories.users_repository import UsersRepository
from finance_tracker_project.services.transactions_service import TransactionsService

sessions_controller = SessionsController()
banks_controller = BanksController()
transactions_controller = TransactionsController()
auths_service = AuthsService()
reports_service = ReportsService()
banks_service = BankAccountsService()
transactions_service = TransactionsService()
users_repo = UsersRepository()
banks_repo = BanksRepository()
transactions_repo = TransactionsRepository()